import { defineConfig } from 'tsdown'

// The gherkin-cli engines, as a plugin install runs them. A plugin installs as its tracked
// files with no node_modules, so check-suite, classify-edit-class, touch-set-correction and
// verify-scenarios cannot import gherkin-cli by package name there. This bundles gherkin-cli
// and everything it imports into one committed, self-contained module in the spec gate's
// vendor dir, which all four import. Rebuild it with `pnpm build:vendor` whenever the
// gherkin-cli pin moves; the vendor test fails while the committed file is stale.
//
// VENDOR_OUT_DIR lets that test build into a scratch dir and compare.
export default defineConfig({
	entry: { 'gherkin-cli': 'node_modules/gherkin-cli/dist/index.js' },
	deps: { alwaysBundle: [/.*/] },
	format: 'esm',
	outExtensions: () => ({ js: '.mjs' }),
	outDir: process.env.VENDOR_OUT_DIR ?? 'skills/spec-gate/vendor',
	clean: false,
	platform: 'node',
	target: 'node22',
	dts: false,
	banner: '// Generated by `pnpm build:vendor` (tsdown.vendor.config.ts) from the gherkin-cli dependency. Do not edit.',
})
